# Generated by Django 5.0 on 2024-07-10 11:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='videos/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assessment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proctoring.assessment')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proctoring.student')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
